### ISSUE TITLE
Possible mistake in the code

### ISSUE THREAD

**Issue by xiang-deng** [iai-group/sigir2017-table#1]
https://github.com/iai-group/sigir2017-table/blob/22ad141a637004b6a4edb4c0d00b0a134aa46464/Population/elastic.py#L376
the `"content"` here seems to be args for `fields_return`, right?
https://github.com/iai-group/sigir2017-table/blob/22ad141a637004b6a4edb4c0d00b0a134aa46464/Population/elastic.py#L227

**Comment by imsure318** [comment]
Thanks.
This arg does not make sense. 
It refers to 'content', but has defined in the body.

**Comment by xiang-deng** [comment]
In cat index, there are two fields `category_n` and `category_n`, while in candidate generation, it's `category`. Which should I use?
https://github.com/iai-group/sigir2017-table/blob/22ad141a637004b6a4edb4c0d00b0a134aa46464/Population/row_evaluation.py#L75

Also, the following code is buggy.
https://github.com/iai-group/sigir2017-table/blob/22ad141a637004b6a4edb4c0d00b0a134aa46464/Population/row_ranking_entities.py#L134-L135
Should I comment out L135? If so, what is `table` in L134, seems this should be doc_id. Also the default field for `ScorerLM` is `catchall`, should it set as `label` here?

**Comment by imsure318** [comment]
Line 75: use the field corresponding to your index (categories in a list).
Line 135: fixed. (with p_l_theta_lm added.)
